### PR TITLE
Local variables view

### PR DESCRIPTION
**Pull request by cyman-ide**
MOTIVATION:
gf has become my go-to debugger front end, but I have always missed the "locals" view that many debuggers have. Without any prior experience with gdb's python API, I tried my hand at cobbling up a solution.

This isn't finished yet. I'm just sharing something I was trying to do in case there is interest in it, in which case I can work on it more.

USAGE:
As it stands, you can add the expression `.locals` to the watch panel to get a view of all of the local variables. The main problem right now is that the "fields" of the locals view don't seem to update when the scope changes unless you delete the expression and recreate it.

TODO:
 - [x] ⚠️ Fix fields not updating as scope changes.
 - [x] Create new UI panel for locals view, or otherwise separate it from the rest of the watch panel.
 - [x] Decouple locals evaluation from watch expression evaluation, so that every expression isn't being string compared to ".locals" every update.
 - [x] Fix stalling issue.

### CODE REVIEW

**Comment by nakst** [comment]
For updating the display as the scope changes, you might want to have a look at how dynamic arrays are implemented: https://github.com/nakst/gf/blob/master/windows.cpp#L1929

For creating a separate panel for the locals, I think you could add a new "Locals" window here https://github.com/nakst/gf/blob/master/gf2.cpp#L1263 using the existing `WatchWindowUpdate` and `WatchWindowFocus` functions but with a new `LocalsWindowCreate` function that can set some data on the `WatchWindow` for it to behave differently. In doing this you could probably also solve the issue of decoupling the local variable listing from the rest of the watch window Python code.

**Comment by cyman-ide** [comment]
This is almost ready, I think, except that there is an issue where a step can cause a stall for a few seconds in specific situations. Seems to be more noticeable if a struct with several fields is open in the panel.

I'm having difficulty finding the cause of the problem, so any insight would be helpful. The implementation in the UI client is a naive n^2 thing, but it still updates instantly 99% of the time. Usually when the stall happens, the console log will show that there was an interrupt, but this might just be a side effect of an operation taking longer than expected.

**Comment by cyman-ide** [comment]
Update: The stall is caused by a paint event sending `gf_valueof` while `programRunning` is true, causing gf to issue a SIGINT and usleep for 1 second. This problem doesn't seem to be exclusive to the locals view, as I've gotten stalls in the regular watch window as well. Still working on a solution.

**Comment by nakst** [comment]
Overall, this looks like a good implementation. But there are some things that need to be addressed in `windows.cpp` before I can merge it:
- Line 940: add a field `int extraRows;`
- Line 966: add a new function
```c
int WatchLastRow(WatchWindow *w) {
	return w->rows.Length() - 1 + w->extraRows;
}
```
- Line 1538: remove this check, and instead check that `w->mode == WATCH_NORMAL` on lines 1793 and 1803.
- Line 1560: change this to `if (!w || w->mode != WATCH_NORMAL) return;`
- Line 1671: remove the variable `int last` and change the `if` condition to `i <= WatchLastRow(w)`
- Line 1691: change this block to
```c
if ((!watch->value || watch->updateIndex != w->updateIndex) && !watch->open) {
	if (programRunning) {
		free(watch->value);
		watch->updateIndex = w->updateIndex;
		WatchEvaluate("gf_valueof", watch);
		watch->value = strdup(evaluateResult);
		char *end = strchr(watch->value, '\n');
		if (end) *end = 0;
	} else if (strcmp(watch->value, "..")) {
		free(watch->value);
		watch->value = strdup(".."); // Indicate the value is stale.
	}
}
```
- Line 1725: change this to `return (WatchLastRow(w) + 1) * rowHeight;`
- Line 1775: replace `w` with `w->mode == WATCH_NORMAL ? w : InterfaceWindowSwitchToAndFocus("Watch")`
- Line 1831: change this to `w->selectedRow = WatchLastRow(w);`
- Line 1873: change this to `} else if (w->selectedRow > WatchLastRow(w)) {`
- Line 1874: change this to `w->selectedRow = WatchLastRow(w);`
- Line 1897: set `w->extraRows = 1;`
- Line 1930: the `memset` is unnecessary, instead write `Array<char *> expressions = {};`
- Lines 1940-1979: code style, expressions like `int watchIndex=0` should be `int watchIndex = 0`, `exprIndex` should be `expressionIndex`, there should be a blank line between 1943-1944 and 1951-1952, and comments should be written in sentence case.

Thanks.

**Comment by cyman-ide** [comment]
I made additional changes so that "Add entry for address" works as expected from the local view.

**Pull request merged**
