### PR TITLE
Add FreeBSD support

### PR DESCRIPTION
**Pull request by hsnyder**
Very minor changes were required to get gf2 building on FreeBSD. None of the changes should affect the previous Linux code path.

### CODE REVIEW

**Comment by nakst** [comment]
I believe the code `if [ "$(uname)" == "FreeBSD" ]; then` uses a GNU Bash extension and will not run on some Linux distros that use other shells like `dash`.

**Comment by nakst** [comment]
Perhaps instead you could make a separate `build_freebsd.sh` file and leave `build.sh` unchanged?

**Comment by hsnyder** [comment]
Done as per your suggestion.

**Comment by hsnyder** [comment]
(To be honest, the FreeBSD code path will almost certainly work in Linux too; `fork`, `setsid`, `dup2` and `execvp` are more common than the `posix_spawn` family ... but I haven't tested it)

**Pull request merged**
