### PR TITLE
[WIP] Fix subpixel glyph rendering

### PR DESCRIPTION
**Pull request by Toctave**
Hi,
I just downloaded gf and on my machine it seems that the subpixel rendering is broken (see the color fringes in the screenshot below, with Emacs on the right for reference).

Screenshot from 2021-07-18 15-58-38

I think that there is an issue with the alpha blending code which is not 100% clear to me, but for now I've just replaced it with a straightforward non-subpixel implementation, and it's already much prettier (left is old, right is new) : 

Screenshot from 2021-07-18 17-25-34

Depending on the resolution of your screen, subpixel glyph rendering might be overkill as well

### CODE REVIEW

**Comment by Toctave** [comment]
Found the issue : no filtering was applied to the subpixel colors, and they were getting blended with the background in sRGB space rather than in linear space. I fixed both issues by applying the advice in https://www.freetype.org/freetype2/docs/reference/ft2-lcd_rendering.html and https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_render_glyph .

Here is a picture, feel free to zoom in (in an editor with linear filtering turned off) to see the effect better : 
Screenshot from 2021-07-18 18-24-28

**Comment by nakst** [comment]
This is what text rendering currently looks like for me:
image
I think there may be differences in how FreeType is configured which is affecting the colour fringes. I'm also concerned by the performance of the sRGB conversions. Because of this, I think it's better to just disable subpixel rendering by default.

**Comment by nakst** [comment]
I have disabled subpixel rendering by default in 0db9ad0. Let me know if this helps.

**Comment by Toctave** [comment]
Sounds good to me, thanks.

It's true that the sRGB conversion might be expensive. I'll try benchmarking it if I have time. That being said, it's something that should easily be SIMD'd if needed. 

As for the freetype config, I'll try using `FT_Library_SetLcdFilter(ui.ft, FT_LCD_FILTER_DEFAULT);` without the sRGB conversion as well. I included it in the same go because it's recommended in the freetype docs, but I guess doing without would give us a good enough result without a performance hit.

**Pull request closed without merging**
