### PR TITLE
fix: making sure the context menu is not hidden when the window is maximized in `UITextbox` elements.

### PR DESCRIPTION
**Pull request by s4my**

### CODE REVIEW

**Comment by nakst** [comment]
Strange, it should try to place the context menu so that it fits on the screen; and this does work on my desktop.
Can you check to see what's happening in the code here? https://github.com/nakst/gf/blob/master/luigi2.h#L5553

**Comment by s4my** [comment]
It seems that `ScreenOfDisplay()` is detecting the wrong height for my screen, it thinks `screen->height` it taller than what it actually is. So it's Xlib bug i guess.

**Comment by s4my** [comment]
It seems that `ScreenOfDisplay()` is detecting the wrong height for my screen, it thinks `screen->height` it taller than what it actually is. So it's an Xlib bug i guess. Even when i change screens `ScreenCount(ui.display)` only detects one screen. So feel free to close this PR.

**Comment by s4my** [comment]
Maybe a better solution is to detect if the menu is about to overflow outside the window bounds, draw it above. So even if the window is not maximized the menu won't ever overflow outside of the window. I noticed that how it's behaving in my web browser.

**Comment by nakst** [comment]
No, now if the original window is positioned slightly offscreen, then the menu may not be fully visible.

Could you not determine why the original code was not working?

**Comment by s4my** [comment]
> No, now if the original window is positioned slightly offscreen, then the menu may not be fully visible.

Ok, in that case the logic just has to be more complicated, we'll have to check if the menu is not off screen too. The menu should never be outside the main window, that how it works in all the examples i gave you.

> Could you not determine why the original code was not working?

I did, did you not read my 1st message? my second monitor is connected with an adapter, which causes problems it seems with Xlib thinking it's resolution height is taller that what it actually is thus the calculations are wrong.
So `if (menu->pointY + height > y + screen->height)` returns false when it should be true, because `screen->height` value is wrong.

**Pull request merged**
